namespace Betsi.ControlPlane;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

/// <summary>Where a tenant is in its lifecycle.</summary>
public enum TenantState
{
    /// <summary>Registered; database creation or first migration not yet complete.</summary>
    Provisioning = 1,
    Active = 2,
    /// <summary>Deliberately taken out of service by an operator. Data is retained.</summary>
    Suspended = 3,
    /// <summary>Provisioning or migration failed. Re-running the operation resumes it.</summary>
    Failed = 4
}

/// <summary>
/// One tenant in the registry: where its database is and what state it is in.
/// </summary>
/// <remarks>
/// Deliberately holds no credentials. <see cref="DatabaseServer"/> names a server profile
/// whose connection string lives in configuration (and in production, a secret store), so a
/// copy of the control-plane database does not hand over access to every tenant's patient
/// records. This is how MVP-007's "registry with encrypted connections" is met.
/// </remarks>
public sealed class TenantRecord
{
    public Guid TenantId { get; set; }
    public string Name { get; set; } = string.Empty;
    public TenantState State { get; set; }
    public string? StateReason { get; set; }

    /// <summary>Key into <c>Tenancy:DatabaseServers</c>.</summary>
    public string DatabaseServer { get; set; } = string.Empty;
    public string DatabaseName { get; set; } = string.Empty;

    /// <summary>The last migration applied to this tenant's database, or null if none.</summary>
    public string? SchemaVersion { get; set; }

    public string? LicenseKey { get; set; }

    /// <summary>
    /// The latest time (UTC) this tenant's licence was evaluated at. Only ever moves forward; see
    /// <see cref="Licensing.LicenseValidator"/> for why.
    /// </summary>
    public DateTime? LicenseHighWaterMark { get; set; }

    /// <summary>
    /// The licence status and licence id last written to the audit log. Stored rather than
    /// held in memory so that a restarted instance or an operator command does not re-audit a
    /// status that has not changed.
    /// </summary>
    public string? RecordedLicenseStatus { get; set; }
    public Guid? RecordedLicenseId { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public byte[] RowVersion { get; set; } = [];
}

/// <summary>
/// An operator or system action against the control plane: provisioning, suspension,
/// migration, licence installation and licence status changes.
/// </summary>
public sealed class ControlPlaneAuditRecord
{
    public long Id { get; set; }
    public Guid? TenantId { get; set; }
    public string Action { get; set; } = string.Empty;
    public string Actor { get; set; } = string.Empty;
    public string Outcome { get; set; } = string.Empty;
    public string? Detail { get; set; }
    public DateTime OccurredAt { get; set; }
}

/// <summary>
/// The control-plane database (spec §3.3): tenant registry and its audit trail.
/// </summary>
/// <remarks>
/// Separate from every tenant database and holding no clinical data, so control-plane access
/// cannot be used to read patient records.
/// </remarks>
public sealed class ControlPlaneDbContext : DbContext
{
    public ControlPlaneDbContext(DbContextOptions<ControlPlaneDbContext> options) : base(options)
    {
    }

    public DbSet<TenantRecord> Tenants => Set<TenantRecord>();
    public DbSet<ControlPlaneAuditRecord> AuditLog => Set<ControlPlaneAuditRecord>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var isSqlServer = Database.ProviderName == "Microsoft.EntityFrameworkCore.SqlServer";

        modelBuilder.HasDefaultSchema("control");

        var tenant = modelBuilder.Entity<TenantRecord>();
        tenant.ToTable("Tenants");
        tenant.HasKey(t => t.TenantId);
        tenant.Property(t => t.TenantId).ValueGeneratedNever();
        tenant.Property(t => t.Name).IsRequired().HasMaxLength(200);
        tenant.Property(t => t.State).IsRequired().HasConversion<string>().HasMaxLength(20);
        tenant.Property(t => t.StateReason).HasMaxLength(1000);
        tenant.Property(t => t.DatabaseServer).IsRequired().HasMaxLength(100);
        tenant.Property(t => t.DatabaseName).IsRequired().HasMaxLength(100);
        tenant.Property(t => t.SchemaVersion).HasMaxLength(150);
        tenant.Property(t => t.LicenseKey).HasMaxLength(8000);
        tenant.Property(t => t.RecordedLicenseStatus).HasMaxLength(30);

        // SQLite has no rowversion, so the token is only generated by SQL Server. Tests that
        // need to prove concurrency behaviour run against SQL Server.
        if (isSqlServer)
            tenant.Property(t => t.RowVersion).IsRowVersion();
        else
            tenant.Ignore(t => t.RowVersion);

        tenant.HasIndex(t => t.Name).IsUnique();

        // Two tenants in one database defeats database-per-tenant (ADR-001), so the database
        // enforces it rather than trusting every code path to check.
        tenant.HasIndex(t => new { t.DatabaseServer, t.DatabaseName }).IsUnique();

        var audit = modelBuilder.Entity<ControlPlaneAuditRecord>();
        audit.ToTable("AuditLog");
        audit.HasKey(a => a.Id);
        audit.Property(a => a.Action).IsRequired().HasMaxLength(100);
        audit.Property(a => a.Actor).IsRequired().HasMaxLength(200);
        audit.Property(a => a.Outcome).IsRequired().HasMaxLength(50);
        audit.Property(a => a.Detail).HasMaxLength(2000);
        audit.HasIndex(a => new { a.TenantId, a.OccurredAt });
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        // Every control-plane timestamp is UTC. Without this, values read back from the
        // database have DateTimeKind.Unspecified and are silently treated as local time.
        configurationBuilder.Properties<DateTime>().HaveConversion<UtcDateTimeConverter>();
        configurationBuilder.Properties<DateTime?>().HaveConversion<UtcDateTimeConverter>();
    }
}

/// <summary>
/// Stores instants as UTC and reads them back marked as UTC.
/// </summary>
/// <remarks>
/// SQL Server's datetime2 carries no time zone, so without this every value read back has
/// <see cref="DateTimeKind.Unspecified"/> and is serialised without a "Z" — which a browser
/// interprets as local time, shifting every deadline on the board by the UTC offset. An
/// unspecified value being written is assumed to already be UTC (every instant in this system
/// comes from a UTC clock); only a value explicitly marked local is converted.
/// </remarks>
public sealed class UtcDateTimeConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<DateTime, DateTime>
{
    public UtcDateTimeConverter()
        : base(
            v => v.Kind == DateTimeKind.Local ? v.ToUniversalTime() : DateTime.SpecifyKind(v, DateTimeKind.Utc),
            v => DateTime.SpecifyKind(v, DateTimeKind.Utc))
    {
    }
}

/// <summary>Builds a control-plane context for <c>dotnet ef</c>. Never connects.</summary>
public sealed class ControlPlaneDesignTimeFactory : IDesignTimeDbContextFactory<ControlPlaneDbContext>
{
    public ControlPlaneDbContext CreateDbContext(string[] args) =>
        new(new DbContextOptionsBuilder<ControlPlaneDbContext>()
            .UseSqlServer(
                "Server=(design-time);Database=betsi_control;Trusted_Connection=True;",
                sql => sql.MigrationsHistoryTable("__EFMigrationsHistory", "control"))
            .Options);
}
